CREATE DATABASE IF NOT EXISTS intellivehicle CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE intellivehicle;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(40) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  dob DATE NOT NULL,
  gender ENUM('male','female','others') NOT NULL,
  city VARCHAR(128) NOT NULL,
  pincode VARCHAR(20) NOT NULL,
  state VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
